platform :ios, '15.0'

target 'Squirrel2iOS' do
  use_frameworks!
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  
end